[project]
name = "biome-leak-guard"
version = "1.0.0"
description = "Watch over biomejs processes and terminate them if they leak memory."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psutil>=7.1.2",
]

[project.scripts]
blguard = "main:main"
blg = "main:main"