[project]
name = "biome-leak-killer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psutil>=7.1.2",
]

[project.scripts]
biomekiller = "main:main"
blk = "main:main"